from pprint import pprint

import datetime as dt

lel = '''[{'day': {'name': 'понедельник'},
  'id': 297,
  'kind': {'name': 'Семинар'},
  'parity': 'Знаменатель',
  'subject': {'id': 9,
              'lab_teacher': None,
              'lecturer': None,
              'my_playlist_url': None,
              'name': 'Промышленные контроллеры',
              'official_playlist_url': None,
              'practic_teacher': None},
  'teacher': {'department': {'abbreviation': 'АПП',
                             'id': 1,
                             'name': 'Автоматизация производственых процессов'},
              'email': None,
              'first_name': 'Руслан',
              'id': 65,
              'kstu_link': None,
              'middle_name': 'Фаритович',
              'phone_number': None,
              'position': None,
              'second_name': 'Сайфулин'},
  'time': '15:00:00'},
 {'day': {'name': 'понедельник'},
  'id': 287,
  'kind': {'name': 'Семинар'},
  'parity': 'Знаменатель',
  'subject': {'id': 4,
              'lab_teacher': None,
              'lecturer': {'second_name': 'Кучер'},
              'my_playlist_url': None,
              'name': 'Маркетинг и бизнес-планирование',
              'official_playlist_url': None,
              'practic_teacher': None},
  'teacher': {'department': None,
              'email': None,
              'first_name': 'Валентина',
              'id': 67,
              'kstu_link': None,
              'middle_name': 'Николаевна',
              'phone_number': None,
              'position': None,
              'second_name': 'Кучер'},
  'time': '11:00:00'},
 {'day': {'name': 'понедельник'},
  'id': 291,
  'kind': {'name': 'Семинар'},
  'parity': 'Знаменатель',
  'subject': {'id': 14,
              'lab_teacher': None,
              'lecturer': None,
              'my_playlist_url': None,
              'name': 'Основы антикоррупционной культуры',
              'official_playlist_url': None,
              'practic_teacher': None},
  'teacher': {'department': None,
              'email': None,
              'first_name': 'Мадина',
              'id': 68,
              'kstu_link': None,
              'middle_name': 'Абдрашитовна',
              'phone_number': None,
              'position': None,
              'second_name': 'Сейдинова'},
  'time': '13:00:00'},
 {'day': {'name': 'вторник'},
  'id': 288,
  'kind': {'name': 'Лекция'},
  'parity': 'Всегда',
  'subject': {'id': 12,
              'lab_teacher': None,
              'lecturer': None,
              'my_playlist_url': None,
              'name': 'Применение SCADA-систем в общепромышленных комплексах',
              'official_playlist_url': None,
              'practic_teacher': None},
  'teacher': {'department': {'abbreviation': 'АПП',
                             'id': 1,
                             'name': 'Автоматизация производственых процессов'},
              'email': None,
              'first_name': 'Алексей',
              'id': 10,
              'kstu_link': 'http://person.kstu.kz/kalinin-alexey-anatolevich/',
              'middle_name': 'Анатольевич',
              'phone_number': None,
              'position': None,
              'second_name': 'Калинин'},
  'time': '11:00:00'},
 {'day': {'name': 'среда'},
  'id': 294,
  'kind': {'name': 'Лекция'},
  'parity': 'Знаменатель',
  'subject': {'id': 14,
              'lab_teacher': None,
              'lecturer': None,
              'my_playlist_url': None,
              'name': 'Основы антикоррупционной культуры',
              'official_playlist_url': None,
              'practic_teacher': None},
  'teacher': {'department': None,
              'email': None,
              'first_name': 'Мадина',
              'id': 68,
              'kstu_link': None,
              'middle_name': 'Абдрашитовна',
              'phone_number': None,
              'position': None,
              'second_name': 'Сейдинова'},
  'time': '13:00:00'},
 {'day': {'name': 'среда'},
  'id': 298,
  'kind': {'name': 'Лекция'},
  'parity': 'Всегда',
  'subject': {'id': 4,
              'lab_teacher': None,
              'lecturer': {'second_name': 'Кучер'},
              'my_playlist_url': None,
              'name': 'Маркетинг и бизнес-планирование',
              'official_playlist_url': None,
              'practic_teacher': None},
  'teacher': {'department': None,
              'email': None,
              'first_name': 'Валентина',
              'id': 67,
              'kstu_link': None,
              'middle_name': 'Николаевна',
              'phone_number': None,
              'position': None,
              'second_name': 'Кучер'},
  'time': '15:00:00'},
 {'day': {'name': 'четверг'},
  'id': 283,
  'kind': {'name': 'Семинар'},
  'parity': 'Знаменатель',
  'subject': {'id': 10,
              'lab_teacher': None,
              'lecturer': None,
              'my_playlist_url': None,
              'name': 'Элементы и устройства автоматики',
              'official_playlist_url': None,
              'practic_teacher': None},
  'teacher': {'department': {'abbreviation': 'АПП',
                             'id': 1,
                             'name': 'Автоматизация производственых процессов'},
              'email': None,
              'first_name': 'Геннадий',
              'id': 30,
              'kstu_link': 'http://person.kstu.kz/em-gennadyi-arkadyevich/',
              'middle_name': 'Аркадиевич',
              'phone_number': None,
              'position': None,
              'second_name': 'Эм'},
  'time': '09:00:00'},
 {'day': {'name': 'пятница'},
  'id': 299,
  'kind': {'name': 'Семинар'},
  'parity': 'Знаменатель',
  'subject': {'id': 6,
              'lab_teacher': None,
              'lecturer': None,
              'my_playlist_url': None,
              'name': 'Силовые преобразовательные устройства',
              'official_playlist_url': None,
              'practic_teacher': None},
  'teacher': {'department': {'abbreviation': 'ЭС',
                             'id': 2,
                             'name': 'Электроснабжение'},
              'email': None,
              'first_name': 'Аркадий',
              'id': 49,
              'kstu_link': 'http://person.kstu.kz/bilichenko-arkadij-petrovich/',
              'middle_name': 'Петрович',
              'phone_number': None,
              'position': None,
              'second_name': 'Биличенко'},
  'time': '15:00:00'},
 {'day': {'name': 'пятница'},
  'id': 295,
  'kind': {'name': 'Семинар'},
  'parity': 'Знаменатель',
  'subject': {'id': 11,
              'lab_teacher': None,
              'lecturer': None,
              'my_playlist_url': None,
              'name': 'Электрические аппараты и элементы автоматизированного '
                      'электропривода',
              'official_playlist_url': None,
              'practic_teacher': None},
  'teacher': {'department': None,
              'email': None,
              'first_name': 'Леонид',
              'id': 31,
              'kstu_link': None,
              'middle_name': 'Израильевич',
              'phone_number': None,
              'position': None,
              'second_name': 'Дайч'},
  'time': '13:00:00'}]
[{'day': {'name': 'понедельник'},
  'id': 292,
  'kind': {'name': 'Лекция'},
  'parity': 'Числитель',
  'subject': {'id': 10,
              'lab_teacher': None,
              'lecturer': None,
              'my_playlist_url': None,
              'name': 'Элементы и устройства автоматики',
              'official_playlist_url': None,
              'practic_teacher': None},
  'teacher': {'department': {'abbreviation': 'АПП',
                             'id': 1,
                             'name': 'Автоматизация производственых процессов'},
              'email': None,
              'first_name': 'Геннадий',
              'id': 30,
              'kstu_link': 'http://person.kstu.kz/em-gennadyi-arkadyevich/',
              'middle_name': 'Аркадиевич',
              'phone_number': None,
              'position': None,
              'second_name': 'Эм'},
  'time': '13:00:00'},
 {'day': {'name': 'понедельник'},
  'id': 286,
  'kind': {'name': 'Лекция'},
  'parity': 'Числитель',
  'subject': {'id': 11,
              'lab_teacher': None,
              'lecturer': None,
              'my_playlist_url': None,
              'name': 'Электрические аппараты и элементы автоматизированного '
                      'электропривода',
              'official_playlist_url': None,
              'practic_teacher': None},
  'teacher': {'department': {'abbreviation': 'АПП',
                             'id': 1,
                             'name': 'Автоматизация производственых процессов'},
              'email': None,
              'first_name': 'Владимир',
              'id': 9,
              'kstu_link': 'http://person.kstu.kz/kaverin-vladimir-viktorovich/',
              'middle_name': 'Викторович',
              'phone_number': None,
              'position': None,
              'second_name': 'Каверин'},
  'time': '11:00:00'},
 {'day': {'name': 'понедельник'},
  'id': 282,
  'kind': {'name': 'Лекция'},
  'parity': 'Числитель',
  'subject': {'id': 6,
              'lab_teacher': None,
              'lecturer': None,
              'my_playlist_url': None,
              'name': 'Силовые преобразовательные устройства',
              'official_playlist_url': None,
              'practic_teacher': None},
  'teacher': {'department': {'abbreviation': 'АПП',
                             'id': 1,
                             'name': 'Автоматизация производственых процессов'},
              'email': None,
              'first_name': 'Софья',
              'id': 5,
              'kstu_link': 'http://person.kstu.kz/vojtkevich-sofya-valentinovna/',
              'middle_name': 'Валентиновна',
              'phone_number': None,
              'position': None,
              'second_name': 'Войткевич'},
  'time': '09:00:00'},
 {'day': {'name': 'вторник'},
  'id': 293,
  'kind': {'name': 'Лекция'},
  'parity': 'Числитель',
  'subject': {'id': 9,
              'lab_teacher': None,
              'lecturer': None,
              'my_playlist_url': None,
              'name': 'Промышленные контроллеры',
              'official_playlist_url': None,
              'practic_teacher': None},
  'teacher': {'department': {'abbreviation': 'АПП',
                             'id': 1,
                             'name': 'Автоматизация производственых процессов'},
              'email': None,
              'first_name': 'Дмитрий',
              'id': 14,
              'kstu_link': 'http://person.kstu.kz/lisitsyn-dmitrij-vladimirovich/',
              'middle_name': 'Владимирович',
              'phone_number': None,
              'position': None,
              'second_name': 'Лисицын'},
  'time': '13:00:00'},
 {'day': {'name': 'вторник'},
  'id': 288,
  'kind': {'name': 'Лекция'},
  'parity': 'Всегда',
  'subject': {'id': 12,
              'lab_teacher': None,
              'lecturer': None,
              'my_playlist_url': None,
              'name': 'Применение SCADA-систем в общепромышленных комплексах',
              'official_playlist_url': None,
              'practic_teacher': None},
  'teacher': {'department': {'abbreviation': 'АПП',
                             'id': 1,
                             'name': 'Автоматизация производственых процессов'},
              'email': None,
              'first_name': 'Алексей',
              'id': 10,
              'kstu_link': 'http://person.kstu.kz/kalinin-alexey-anatolevich/',
              'middle_name': 'Анатольевич',
              'phone_number': None,
              'position': None,
              'second_name': 'Калинин'},
  'time': '11:00:00'},
 {'day': {'name': 'среда'},
  'id': 298,
  'kind': {'name': 'Лекция'},
  'parity': 'Всегда',
  'subject': {'id': 4,
              'lab_teacher': None,
              'lecturer': {'second_name': 'Кучер'},
              'my_playlist_url': None,
              'name': 'Маркетинг и бизнес-планирование',
              'official_playlist_url': None,
              'practic_teacher': None},
  'teacher': {'department': None,
              'email': None,
              'first_name': 'Валентина',
              'id': 67,
              'kstu_link': None,
              'middle_name': 'Николаевна',
              'phone_number': None,
              'position': None,
              'second_name': 'Кучер'},
  'time': '15:00:00'},
 {'day': {'name': 'четверг'},
  'id': 289,
  'kind': {'name': 'Лабораторное занятие'},
  'parity': 'Числитель',
  'subject': {'id': 10,
              'lab_teacher': None,
              'lecturer': None,
              'my_playlist_url': None,
              'name': 'Элементы и устройства автоматики',
              'official_playlist_url': None,
              'practic_teacher': None},
  'teacher': {'department': {'abbreviation': 'АПП',
                             'id': 1,
                             'name': 'Автоматизация производственых процессов'},
              'email': None,
              'first_name': 'Геннадий',
              'id': 30,
              'kstu_link': 'http://person.kstu.kz/em-gennadyi-arkadyevich/',
              'middle_name': 'Аркадиевич',
              'phone_number': None,
              'position': None,
              'second_name': 'Эм'},
  'time': '11:00:00'},
 {'day': {'name': 'четверг'},
  'id': 284,
  'kind': {'name': 'Лабораторное занятие'},
  'parity': 'Числитель',
  'subject': {'id': 12,
              'lab_teacher': None,
              'lecturer': None,
              'my_playlist_url': None,
              'name': 'Применение SCADA-систем в общепромышленных комплексах',
              'official_playlist_url': None,
              'practic_teacher': None},
  'teacher': {'department': {'abbreviation': 'АПП',
                             'id': 1,
                             'name': 'Автоматизация производственых процессов'},
              'email': None,
              'first_name': 'Алексей',
              'id': 10,
              'kstu_link': 'http://person.kstu.kz/kalinin-alexey-anatolevich/',
              'middle_name': 'Анатольевич',
              'phone_number': None,
              'position': None,
              'second_name': 'Калинин'},
  'time': '09:00:00'},
 {'day': {'name': 'пятница'},
  'id': 285,
  'kind': {'name': 'Лабораторное занятие'},
  'parity': 'Числитель',
  'subject': {'id': 6,
              'lab_teacher': None,
              'lecturer': None,
              'my_playlist_url': None,
              'name': 'Силовые преобразовательные устройства',
              'official_playlist_url': None,
              'practic_teacher': None},
  'teacher': {'department': {'abbreviation': 'АПП',
                             'id': 1,
                             'name': 'Автоматизация производственых процессов'},
              'email': None,
              'first_name': 'Руслан',
              'id': 65,
              'kstu_link': None,
              'middle_name': 'Фаритович',
              'phone_number': None,
              'position': None,
              'second_name': 'Сайфулин'},
  'time': '09:00:00'},
 {'day': {'name': 'пятница'},
  'id': 296,
  'kind': {'name': 'Лабораторное занятие'},
  'parity': 'Числитель',
  'subject': {'id': 9,
              'lab_teacher': None,
              'lecturer': None,
              'my_playlist_url': None,
              'name': 'Промышленные контроллеры',
              'official_playlist_url': None,
              'practic_teacher': None},
  'teacher': {'department': {'abbreviation': 'АПП',
                             'id': 1,
                             'name': 'Автоматизация производственых процессов'},
              'email': None,
              'first_name': 'Шокан',
              'id': 3,
              'kstu_link': 'http://person.kstu.kz/amankeldin-shokan-amankeldyuly/',
              'middle_name': 'Аманкельдыұлы',
              'phone_number': None,
              'position': None,
              'second_name': 'Аманкельдин'},
  'time': '13:00:00'},
 {'day': {'name': 'пятница'},
  'id': 290,
  'kind': {'name': 'Лабораторное занятие'},
  'parity': 'Числитель',
  'subject': {'id': 11,
              'lab_teacher': None,
              'lecturer': None,
              'my_playlist_url': None,
              'name': 'Электрические аппараты и элементы автоматизированного '
                      'электропривода',
              'official_playlist_url': None,
              'practic_teacher': None},
  'teacher': {'department': {'abbreviation': 'ЭС',
                             'id': 2,
                             'name': 'Электроснабжение'},
              'email': None,
              'first_name': 'Александр',
              'id': 44,
              'kstu_link': 'http://person.kstu.kz/taranov-aleksandr-viktorovich/',
              'middle_name': 'Викторович',
              'phone_number': None,
              'position': None,
              'second_name': 'Таранов'},
  'time': '11:00:00'}]
'''


print(len(lel))